"""
End-to-End Pipeline Runner
Executes: data loading → preprocessing → feature engineering → model training
→ evaluation → expected loss → stress testing.

Usage:
    python run_pipeline.py
"""

import os
import json
import logging
import pandas as pd
import numpy as np

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(levelname)s | %(message)s")
logger = logging.getLogger("pipeline")


def load_raw_data(raw_dir: str = "data/raw") -> dict:
    """Load all raw CSVs generated by the data generator."""
    logger.info("=" * 60)
    logger.info("STEP 1: Loading raw data")
    logger.info("=" * 60)
    datasets = {}
    for name in ["customers", "accounts", "credit_cards", "statements",
                 "transactions", "payments", "delinquencies", "defaults",
                 "macro_variables"]:
        path = os.path.join(raw_dir, f"{name}.csv")
        datasets[name] = pd.read_csv(path)
        logger.info(f"Loaded {name}: {datasets[name].shape}")
    return datasets


def main():
    # Step 1: Load
    datasets = load_raw_data()

    # Step 2: Preprocess
    logger.info("=" * 60)
    logger.info("STEP 2: Preprocessing")
    logger.info("=" * 60)
    from src.pipelines.preprocessing import DataPreprocessor
    preprocessor = DataPreprocessor()
    processed = preprocessor.preprocess_all(datasets)

    # Step 3: Feature engineering
    logger.info("=" * 60)
    logger.info("STEP 3: Feature engineering")
    logger.info("=" * 60)
    from src.pipelines.feature_pipeline import CreditFeatureEngineer
    engineer = CreditFeatureEngineer()
    feature_table = engineer.build_feature_table(processed)

    os.makedirs("data/processed", exist_ok=True)
    feature_table.to_csv("data/processed/feature_table.csv", index=False)
    logger.info("Saved feature table to data/processed/feature_table.csv")

    # Save a small sample for the repo
    os.makedirs("data/sample", exist_ok=True)
    feature_table.head(100).to_csv("data/sample/feature_table_sample.csv", index=False)

    # Step 4: Train models
    logger.info("=" * 60)
    logger.info("STEP 4: Model training")
    logger.info("=" * 60)
    from src.models.train import CreditRiskModelTrainer
    trainer = CreditRiskModelTrainer()
    training_output = trainer.train_all(feature_table)

    # Step 5: Model comparison
    logger.info("=" * 60)
    logger.info("STEP 5: Model comparison")
    logger.info("=" * 60)
    from src.models.evaluate import ModelEvaluator
    evaluator = ModelEvaluator()
    comparison = evaluator.compare_models(training_output["results"])
    comparison.to_csv("reports/model_comparison.csv", index=False)

    # Save metrics for the API
    metrics_export = {
        name: {k: v for k, v in m.items()
               if k not in ["lift_data", "classification_report", "confusion_matrix"]}
        for name, m in training_output["results"].items()
    }
    metrics_export["best_model"] = training_output["best_model"]
    with open("models/metrics.json", "w") as f:
        json.dump(metrics_export, f, indent=2)

    # Step 6: Expected loss
    logger.info("=" * 60)
    logger.info("STEP 6: Expected loss calculation")
    logger.info("=" * 60)
    from src.risk.expected_loss import ExpectedLossCalculator
    el_calc = ExpectedLossCalculator()

    cards = datasets["credit_cards"].set_index("customer_id")
    ft = feature_table.set_index("customer_id")
    common = ft.index.intersection(cards.index)

    credit_limits = cards.loc[common, "credit_limit"]
    balances = ft.loc[common, "latest_balance"].fillna(0)
    pd_values = ft.loc[common, "default_probability"].fillna(ft["default_probability"].mean())

    el_results = el_calc.compute_expected_loss(pd_values, credit_limits, balances)
    portfolio = el_calc.portfolio_summary(el_results)
    logger.info(f"Portfolio summary: {json.dumps(portfolio, indent=2)}")

    with open("reports/portfolio_summary.json", "w") as f:
        json.dump(portfolio, f, indent=2)

    # Step 7: Stress testing
    logger.info("=" * 60)
    logger.info("STEP 7: Stress testing")
    logger.info("=" * 60)
    from src.risk.stress_testing import StressTester
    tester = StressTester()
    model = training_output["models"][training_output["best_model"]]

    ft_reset = feature_table.set_index("customer_id").loc[common].reset_index()
    stress_results = tester.run_stress_test(
        model, ft_reset, training_output["feature_names"],
        credit_limits.reset_index(drop=True),
        balances.reset_index(drop=True),
    )

    with open("reports/stress_test_results.json", "w") as f:
        json.dump(stress_results, f, indent=2)
    logger.info(f"Stress test results: {json.dumps(stress_results, indent=2)}")

    logger.info("=" * 60)
    logger.info("PIPELINE COMPLETE")
    logger.info(f"Best model: {training_output['best_model']}")
    logger.info("Outputs: models/, reports/, data/processed/")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
